contiamo/openapi-generator-go

pkg/generators/models/go_type_from_ref.go
pkg/generators/models/testdata/cases/validation/expected/model_address.go
pkg/generators/models/testdata/cases/validation/expected/model_person.go
pkg/generators/models/testdata/cases/validation/generated/model_address.go
pkg/generators/models/testdata/cases/validation/generated/model_person.go

default to 32 bit numbers to avoid an incompatible change in the typesystem (int32 and int64 behave differently when serializing via json)

default to 32 bit numbers

---

pkg/generators/models/models.go
pkg/generators/models/models_test.go
pkg/generators/models/templates.go
pkg/generators/models/testdata/cases/toplevel_object_with_additional_properties/api.yaml
pkg/generators/models/testdata/cases/toplevel_object_with_additional_properties/expected/model_bar.go
pkg/generators/models/testdata/cases/toplevel_object_with_additional_properties/expected/model_baz.go
pkg/generators/models/testdata/cases/toplevel_object_with_additional_properties/expected/model_foo.go
pkg/generators/models/testdata/cases/toplevel_object_with_additional_properties/expected/model_quak.go
pkg/generators/models/testdata/cases/toplevel_object_with_additional_properties/generated/model_bar.go
pkg/generators/models/testdata/cases/toplevel_object_with_additional_properties/generated/model_baz.go
pkg/generators/models/testdata/cases/toplevel_object_with_additional_properties/generated/model_foo.go
pkg/generators/models/testdata/cases/toplevel_object_with_additional_properties/generated/model_quak.go

Before this change all objects with no props on the toplevel got rendered to map[string]interface{}.
I basically want this to render this api spec:
```
LinkOverviewGroups:
type: object
description: mapping from linkType -> list of links
additionalProperties:
type: array
items:
$ref: "#/components/schemas/LinkResponse"
```
I added a testcase for this.

add support for toplevel models that are map[string]Something

---

pkg/generators/models/generate.go
pkg/generators/models/models_test.go
pkg/generators/models/testdata/cases/model_from_path_body/api.yaml
pkg/generators/models/testdata/cases/model_from_path_body/expected/model_foo.go
pkg/generators/models/testdata/cases/model_from_path_body/expected/model_my_op_body.go
pkg/generators/models/testdata/cases/model_from_path_body/generated/model_foo.go
pkg/generators/models/testdata/cases/model_from_path_body/generated/model_my_op_body.go

This simply preprocesses the spec and adds models for all body definitions in the pathes part of the spec. 
This does NOT cover the request parameters for now.

add models for body definitions in the paths part of the spec.

---

go.sum
pkg/generators/router/router.go
pkg/generators/router/router_test.go

`OperationID` is now cased before processing and there is a uniqueness
check of the converted value across the spec.
Also, case `x-handler-group` before processing, so we group by
properly cased name instead of the original value.
No ticket, the bug found by @trusch 
New unit tests cover the change.

Make sure OperationID is unique and cased properly

---

pkg/generators/models/generate.go
pkg/generators/models/models.go
pkg/generators/models/models_test.go
pkg/generators/models/testdata/cases/parameter_model/api.yaml
pkg/generators/models/testdata/cases/parameter_model/expected/model_get_foo_query_parameters.go
pkg/generators/models/testdata/cases/parameter_model/generated/model_get_foo_query_parameters.go

add support for generating query parameter models.
This will generate a `${OP_ID}QueryParameters` struct for each operation in the spec.
I added a non trivial test + I ran it on hub
- [?] Requires updates to the documentation.

add support for generating query parameter models.

---

pkg/generators/models/models.go
pkg/generators/models/templates.go
pkg/generators/models/testdata/cases/embedded_type/api.yaml
pkg/generators/models/testdata/cases/embedded_type/expected/model_sub1.go
pkg/generators/models/testdata/cases/embedded_type/expected/model_sub3.go
pkg/generators/models/testdata/cases/embedded_type/expected/model_top.go
pkg/generators/models/testdata/cases/embedded_type/generated/model_sub1.go
pkg/generators/models/testdata/cases/embedded_type/generated/model_sub3.go
pkg/generators/models/testdata/cases/embedded_type/generated/model_top.go

Now schemas which are extended aliases of value types are supported.
For example, you can define a schema which has `type: boolean` and then
refer to this schema from another schema. Before this caused a
generation error.
No ticket, noticed the bug when worked on another task.
I modified an existing test case that now tests the new code.

Add support for value type schemas

---

pkg/generators/models/models.go
pkg/generators/models/testdata/cases/oneof/api.yaml
pkg/generators/models/testdata/cases/oneof/expected/model_bar.go
pkg/generators/models/testdata/cases/oneof/generated/model_bar.go

fix: use interface for oneOf
the map is the incorrect format for a oneof of primitave values, interface is easier to workwith
fix: do not use map[string]interface fallback for allOf
allOf has improved and proper support now, so this fallback is not needed

fix: make toplevel oneofs translate to empty interface instead of object

---

pkg/filters/openapi.go
pkg/filters/openapi_test.go
pkg/filters/testdata/filter_without_responses_component/filter.txt
pkg/filters/testdata/filter_without_responses_component/out.yaml
pkg/filters/testdata/source_without_responses_component.yaml

The `components.responses` is an optional section of the API spec. This
fix allows us to filter  API specs that omit this section.
NA
New unit test

fix: Allow responses section in components to be omitted

---

pkg/generators/models/templates.go
pkg/generators/models/testdata/cases/oneof/expected/model_bar.go
pkg/generators/models/testdata/cases/oneof/expected/model_baz.go
pkg/generators/models/testdata/cases/oneof/generated/model_bar.go
pkg/generators/models/testdata/cases/oneof/generated/model_baz.go

Extend the template for `oneOf` so that each possible sub-type has a
corresponding `From*` method that allows the caller to safely set the
data for the oneOf model.
Updated unit tests and experimenting with it in a Hub feature branch

feat: Add From* methods to set oneOf data models

---

pkg/generators/models/templates.go
pkg/generators/models/testdata/cases/oneof/expected/model_bar.go
pkg/generators/models/testdata/cases/oneof/expected/model_baz.go
pkg/generators/models/testdata/cases/oneof/generated/model_bar.go
pkg/generators/models/testdata/cases/oneof/generated/model_baz.go

The MarshalJSON interface needs to be implemented on a value
reciever. When it is a pointer receiver, then you can _only_ marshal
pointers of the type.  Values of the type will just marshal to an empty
json object. This makes the types much harder or impossible to use.
Tested in Hub to fix a failing validation test

fix: MarshalJSON should not have pointer reciever

---

cmd/openapi-generator-go/cmd/merge.go
pkg/generators/models/models.go

This adds the `merge` subcommand to the generator, so that it now contains all functionality needed for all our openapi needs.
That way we can remove the generate.go cmd from hub for example which will remove the dependency on idp for updating the models within hub. 
The command will be used like this:
```
openapi-generator-go merge --base openapi/base.yaml --dir openapi/parts --spec api.yaml
```

expose the merge package as command

---

.github/workflows/conventional-commits.yaml

The workflow will enforce that all PR titles start with the conventional commit prefix
NA 
WIP, this PR will verify itself

ci: Add workflow to enforce conventional commit titles

---

pkg/generators/models/models.go
pkg/generators/models/models_test.go
pkg/generators/models/testdata/cases/allof_mixin_skipping/api.yaml
pkg/generators/models/testdata/cases/allof_mixin_skipping/expected/model_column_metadata.go
pkg/generators/models/testdata/cases/allof_mixin_skipping/expected/model_column_type.go
pkg/generators/models/testdata/cases/allof_mixin_skipping/expected/model_column_type_metadata.go
pkg/generators/models/testdata/cases/allof_mixin_skipping/expected/model_nullability.go
pkg/generators/models/testdata/cases/allof_mixin_skipping/generated/model_column_metadata.go
pkg/generators/models/testdata/cases/allof_mixin_skipping/generated/model_column_type.go
pkg/generators/models/testdata/cases/allof_mixin_skipping/generated/model_column_type_metadata.go
pkg/generators/models/testdata/cases/allof_mixin_skipping/generated/model_nullability.go
pkg/generators/models/testdata/cases/allof_self_reference/api.yaml

Add logic to skip semantically empty schemas inside an allOf. For
example, skipping items that only modify the description. It would be
better to bubble up some of this metadata, but this would require a
significant refactor of the object handling. This change should reduce
the number of situations that result in inline structs being generated,
thus improving the resulting code quality. The tradeoff is that the code
comments are a little less good. But the improved types seem to be worth
it.
None, this resolves an issue in Hub which is caused by #48 
A new unit test has been added that copies the troublesome api schema  and verifies that it generates the expected model (modulo the description)

feat: improve description handling in allOfs

---

pkg/generators/models/templates/oneof.gotpl
pkg/generators/models/testdata/cases/nested_inline_arrays/expected/model_geometry.go
pkg/generators/models/testdata/cases/nested_inline_arrays/generated/model_geometry.go
pkg/generators/models/testdata/cases/oneof_mapped_discriminator/api.yaml
pkg/generators/models/testdata/cases/oneof_mapped_discriminator/expected/mode_test.go
pkg/generators/models/testdata/cases/oneof_mapped_discriminator/expected/model_error.go
pkg/generators/models/testdata/cases/oneof_mapped_discriminator/expected/model_external_error.go
pkg/generators/models/testdata/cases/oneof_mapped_discriminator/generated/model_error.go
pkg/generators/models/testdata/cases/oneof_mapped_discriminator/generated/model_external_error.go
pkg/generators/models/testdata/cases/oneof_unmapped_discriminator/expected/model_error.go
pkg/generators/models/testdata/cases/oneof_unmapped_discriminator/generated/model_error.go

Call the correct validation method instead of creating a validation loop
recusion loop. Add a test to verify that valdiation does return an error
as expected, instead of a panic.
Signed-off-by: Lucas Roesler <roesler.lucas@gmail.com>
NA found it while trying to add a new discriminated oneOf in hub
New unit test

fix: prevent validation loop in discriminated oneOf

---

go.mod
go.sum
pkg/merge/openapi.go

Felix had a hard to spot bug where the merge command of the generator failed to merge some `.DS-STORE` files which were automatically created by some other tool, but ignored by git.
This will now silently ignore all files without a `.yaml` or `.yml` extension.

feat: ignore non-yaml files in the merge command

---

pkg/generators/router/head_operation_test.go
pkg/generators/router/router.go
pkg/generators/router/testdata/head_operation/api.yaml
pkg/generators/router/testdata/head_operation/expected/router.go
pkg/generators/router/testdata/head_operation/generated/router.go

This PR adds support for HEAD operations.
A test has been added that generates code from a simple `api.yaml` that contains a HEAD operation on a path and compares it to the expected result.

feat: add HTTP HEAD operation

---

pkg/generators/models/models.go
pkg/generators/models/models_test.go
pkg/generators/models/testdata/cases/allof1/expected/model_foo.go
pkg/generators/models/testdata/cases/allof1/generated/model_foo.go
pkg/generators/models/testdata/cases/embedded_type/expected/model_top.go
pkg/generators/models/testdata/cases/embedded_type/generated/model_top.go
pkg/generators/models/testdata/cases/not_required_not_nullable_object/api.yaml
pkg/generators/models/testdata/cases/not_required_not_nullable_object/expected/model_foo.go
pkg/generators/models/testdata/cases/not_required_not_nullable_object/expected/model_foo_bar.go
pkg/generators/models/testdata/cases/not_required_not_nullable_object/generated/model_foo.go
pkg/generators/models/testdata/cases/not_required_not_nullable_object/generated/model_foo_bar.go
pkg/generators/models/testdata/cases/validation/expected/model_person.go
pkg/generators/models/testdata/cases/validation/generated/model_person.go

Changes:
1. If a property is not required and not explicitly nullable, set a pointer so that it can be omitted when the generated Go struct is marshaled.
2. Add a test to validate the behaviour.
3. Fix the test numbering.
4. Verify and update tests that are impacted by this change.
#90 
Added a test case to ensure the change works as expected.

feat!: Set pointers for non required not nullable objects

---

.goreleaser.yaml
Makefile
cmd/openapi-generator-go/cmd/filter.go
cmd/openapi-generator-go/cmd/merge.go
cmd/openapi-generator-go/cmd/models.go
cmd/openapi-generator-go/cmd/router.go
go.mod
main.go
pkg/generators/models/generate.go
pkg/generators/models/go_type_from_ref.go
pkg/generators/models/models.go
pkg/generators/models/templates.go
pkg/generators/router/router.go

Add v2 to all of the module imports and the go.mod to prepare a v2 release.
Release-As: 2.0.0

chore: bump go module to v2

---

go.mod
pkg/generators/models/models.go
pkg/generators/models/models_test.go
pkg/generators/models/testdata/cases/allOf_enum_merging_and_validation/api.yaml
pkg/generators/models/testdata/cases/allOf_enum_merging_and_validation/expected/model_connection.go
pkg/generators/models/testdata/cases/allOf_enum_merging_and_validation/generated/model_connection.go
pkg/generators/models/testdata/cases/allof_nesting/api.yaml
pkg/generators/models/testdata/cases/allof_nesting/expected/model_base_entity.go
pkg/generators/models/testdata/cases/allof_nesting/expected/model_org_entity.go
pkg/generators/models/testdata/cases/allof_nesting/expected/model_updatable_entity.go
pkg/generators/models/testdata/cases/allof_nesting/generated/model_base_entity.go
pkg/generators/models/testdata/cases/allof_nesting/generated/model_org_entity.go
pkg/generators/models/testdata/cases/allof_nesting/generated/model_updatable_entity.go

Adjust the schema merge logic to include allOf resolution. This ensures that nested allOf's are correctly merged together.
Adjust some of the model properties generation to handle some edge cases that were discovered for singleton allOfs.
Resolves #94

fix: ensure nestd allOfs are correctly resolved

---

pkg/generators/models/go_type_from_ref.go
pkg/generators/models/testdata/cases/parameter_model/api.yaml
pkg/generators/models/testdata/cases/parameter_model/expected/model_get_foo_query_parameters.go
pkg/generators/models/testdata/cases/parameter_model/expected/model_referenced_status.go
pkg/generators/models/testdata/cases/parameter_model/generated/model_get_foo_query_parameters.go
pkg/generators/models/testdata/cases/parameter_model/generated/model_referenced_status.go

PR 1 for #100 
Make sure that in case a $ref is used the TypeName is formatted (more) properly in PascalCase
[#100](https://github.com/contiamo/openapi-generator-go/issues/100)
Tests introduced in parameter-model api.yaml

fix: Not all schema references are properly formatted GoTypes

---

pkg/filters/openapi.go
pkg/filters/openapi_test.go
pkg/filters/testdata/source_with_request_bodies_component.yaml
pkg/filters/testdata/source_with_request_bodies_component/filter.txt
pkg/filters/testdata/source_with_request_bodies_component/out.yaml

https://github.com/contiamo/openapi-generator-go/issues/153
unit test

fix: filter missing schema when request bodies are defined
